[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@aave/=node_modules/@aave/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    'src/=src/',
]
solc-version = "0.8.10"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
libraries = [
    "src/core/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x763B2a4EbA91c3667a74Ba87A7142be3282FC1C2",
    "src/core/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0xa6265a8cE6F89610d3f97851abcf7F8203B006FB",
    "src/core/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x54C33c8669D52Bb0cd6682dB419483a1e86D8e67",
    "src/core/protocol/libraries/logic/EModeLogic.sol:EModeLogic:0xC8CB15Bc73B7f5f95Af33AEce738bC9B62Cb28D9",
    "src/core/protocol/libraries/logic/BridgeLogic.sol:BridgeLogic:0x342019c99EA2869E1233bB461420078C149a00f1",
    "src/core/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0x306ca8E36c1DcC1E160f94d1Eb5Fd97CEa889871",
    "src/core/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x7954F3efe905D4f2690a05a594886706F424327f",
    "src/core/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x30777a478886eCFcA0DC8B023e4Fd19b133D616F",
    ]
[etherscan]
t_opBNB = { key = "${TOPBNB_ETHERSCAN_API_KEY}", chain=5611, url="https://open-platform.nodereal.io/${NODEREAL_KEY}/op-bnb-testnet/contract/" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", chain=56, url="https://api.bscscan.com/api"}
chapel = { key = "${CHAPEL_ETHERSCAN_API_KEY}", chain=97, url="https://api-testnet.bscscan.com/api"}

[default.rpc_endpoints]
bsc = "https://bsc-dataseed1.binance.org/"
chapel = "https://data-seed-prebsc-1-s1.binance.org:8545/"

[profile.wombat]
test = 'test/ATokenStaker/WombatStaker'

[profile.magpie]
test = 'test/ATokenStaker/MagpieStaker'